version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-hogar360
    environment:
      MYSQL_ROOT_PASSWORD: filomena19
      MYSQL_DATABASE: catalogdb
      MYSQL_USER: root
      MYSQL_PASSWORD: filomena19
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
